/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestErc1155 } from "./TestErc1155";
export type { TestErc20 } from "./TestErc20";
export type { TestErc721 } from "./TestErc721";
export type { TestWETH } from "./TestWETH";
