/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iArtWorkNftSol from "./IArtWorkNFT.sol";
export type { iArtWorkNftSol };
export type { IERC721Fingerprint } from "./IERC721Fingerprint";
export type { IWETH } from "./IWETH";
