/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721Fingerprint,
  IERC721FingerprintInterface,
} from "../../../contracts/interfaces/IERC721Fingerprint";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bundleId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "fingerprint",
        type: "bytes32",
      },
    ],
    name: "verifyFingerprint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721Fingerprint__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721FingerprintInterface {
    return new utils.Interface(_abi) as IERC721FingerprintInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Fingerprint {
    return new Contract(address, _abi, signerOrProvider) as IERC721Fingerprint;
  }
}
