/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestErc1155__factory } from "./TestErc1155__factory";
export { TestErc20__factory } from "./TestErc20__factory";
export { TestErc721__factory } from "./TestErc721__factory";
export { TestWETH__factory } from "./TestWETH__factory";
